Alistair/4725 adds usertaskreminder
THIS-Institute/thiscovery_admin pull request #43
Opened 2022-09-07 14:39 UTC by alistairclark

https://this.tpondemand.com/RestUI/Board.aspx#page=profile&boardPopup=userstory/4725/silent

I've held off on adding the `reminder_details` `JSONField` for now, as it's not clear if it will be needed for the time being and I can add later if needed. Can add this now if that's preferred though.

2022-09-07 15:15 UTC, afs25 approved these changes

2022-09-07 15:56 UTC, this-andy requested changes

2022-09-08 08:15 UTC, alistairclark commented on thiscovery_admin/projects/admin.py
> +class UserTaskReminderInline(ReadOnlyMixin, nested_admin.NestedTabularInline):
The model itself does inherit from `TimeStampedModel`, so I think this is covered. I've added `id` and `modified` into both the inline and the model admin now though.

2022-09-08 08:45 UTC, sophiemachin commented on thiscovery_admin/projects/migrations/0076_usertaskreminder.py
> +                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
I'd prefer it if column names were more descriptive that just 'id', so this would be 'user_task_reminder_id' to make joins to this table a lot more readable. I realise this goes against the naming convention of all the other tables, so feel free to disregard this suggestion if it would be more confusing to change it.

2022-09-08 09:54 UTC, sophiemachin commented on thiscovery_admin/projects/models.py
> +    reminder_type = models.CharField(max_length=10, choices=REMINDER_TYPES)
Do we need to add a CheckConstraint for REMINDER_TYPES? I think this only works at the admin interface level and doesn't restrict the actual database

2022-09-08 10:13 UTC, sophiemachin approved these changes

2022-09-08 11:31 UTC, this-andy commented on thiscovery_admin/projects/admin.py
> +class UserTaskReminderInline(ReadOnlyMixin, nested_admin.NestedTabularInline):
Ah yes, overlooked that! So, yes, that's fine

2022-09-08 12:35 UTC, merged