4869 Add UserListMembership table
THIS-Institute/thiscovery_admin pull request #54
Opened 2023-03-13 12:07 UTC by sophiemachin

2023-03-13 12:07 UTC, this-andy commented
https://this.tpondemand.com/entity/4869

2023-03-13 15:21 UTC, this-andy approved these changes

2023-03-31 12:38 UTC, sophiemachin commented
@this-andy This is also ready

2023-03-31 15:21 UTC, this-andy requested changes

2023-03-31 15:21 UTC, this-andy commented on thiscovery_admin/projects/migrations/0081_userlistmembership.py
> +                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.userlist')),
How are these cascade deletes working.  It looks like rows will be deleted from userproject and userlist if the membership is deleted.  It may be just odd Django syntax that is confusing me.  Can you confirm it's actually the other way round?

2023-03-31 15:23 UTC, sophiemachin commented on .gitignore
> +thiscovery_admin/settings/prod.py
Oh i see what you mean, mine are called prod. I'll update that now

2023-03-31 15:27 UTC, sophiemachin commented on thiscovery_admin/projects/migrations/0081_userlistmembership.py
> +                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.userlist')),
Yes this confused me too, it says that this row can be deleted if the referenced key is deleted

https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ForeignKey.on_delete

2023-04-11 10:36 UTC, this-andy approved these changes

2023-04-11 10:40 UTC, merged